### ISSUE TITLE
Student at Boston University looking for teammates 

### ISSUE THREAD

**Issue by mjolewis** [fix-the-internet/mozilla-builders#5]
Open to ideas!

**Comment by guptariti** [comment]
Hey! I'm actually from Northeastern University (lol). I'm an undergraduate computer science student with experience in full-stack development. I'm down to team up and discuss some ideas if you'd like.

**Comment by ShaswatJBabhulgaonkar** [comment]
Hello !!! I am currently a master's student in computer science. Having a couple of years of experience as a Software Developer, I am proficient in various front-end and back-end technologies along with machine learning and deep learning technologies. Being a Software Developer I am proficient with Java, Python, HTML, CSS, Javascript, React, Node.js and implementation of various machine learning and deep learning algorithms in my academic projects. My personal website:- https://shaswatjbabhulgaonkar.github.io/
You can have a look at my projects on my Github:- https://github.com/ShaswatJBabhulgaonkar and my profile at Linkedin. You can reach me out at my email shaswatjbabhulgaonkar@gmail.com

**Comment by nataliescottdavidson** [comment]
Would y'all consider working on a decentralized videoconferencing platform? IE peer-to-peer Zoom. My understanding is that this would be possible using WebRTC. Another idea I have is a WebRTC based platform for IP cameras which would allow streaming to browser without using an intermediate media server.

**Comment by guptariti** [comment]
Hey! So I like the idea of a decentralized video conferencing platform. My only question is how would we market it to be unique or different from platforms like Zoom or Microsoft Teams that you can download.

**Comment by chaigoyal** [comment]
Hey! I'm an EECS and Business (MET) student at UC Berkeley (www.linkedin.com/in/chaigoyal). I can join and work on much of the non-technical work (and of course help with technical as demand dictates). Let me know if any of you want to team up.

**Comment by KadeMorton** [comment]
Is security something you're interested in? https://github.com/Panopticon-Project/panopticon-admin is my project, I'm looking to build a solution that will enable various parties to consume the information being captured in this project.

**Comment by mjolewis** [comment]
> Hey! I'm actually from Northeastern University (lol). I'm an undergraduate computer science student with experience in full-stack development. I'm down to team up and discuss some ideas if you'd like.

Hey! Definitely interested. Small world, too!

**Comment by mjolewis** [comment]
> Would y'all consider working on a decentralized videoconferencing platform? IE peer-to-peer Zoom. My understanding is that this would be possible using WebRTC. Another idea I have is a WebRTC based platform for IP cameras which would allow streaming to browser without using an intermediate media server.

This sounds like a cool idea!

**Comment by nataliescottdavidson** [comment]
> > Would y'all consider working on a decentralized videoconferencing platform? IE peer-to-peer Zoom. My understanding is that this would be possible using WebRTC. Another idea I have is a WebRTC based platform for IP cameras which would allow streaming to browser without using an intermediate media server.
> 
> This sounds like a cool idea!

Here is the [issue](https://github.com/fix-the-internet/spring-mvp-lab/issues/9). It contains link to meeting tomorrow at 2PM EST. Please attend if you are at all interested!

**Comment by efeichen** [comment]
Hi @mjolewis! I'm an undergrad at UC San Diego studying Computer Science. I have experience with web development and UI/UX feel free to check out my [LinkedIn](https://www.linkedin.com/in/efeichen/) and my GitHub profile. I'm down to discuss ideas as well! Feel free to reach out to me on the Slack channel and email @ kec001@ucsd.edu
