### ISSUE TITLE
[LOOKING FOR TEAM] Full-stack developer

### ISSUE THREAD

**Issue by filipecatraia** [fix-the-internet/mozilla-builders#91]
Hey! My name's Filipe and I'm looking for a team, in case my own idea doesn't qualify for MB. I'm a full-stack developer (Node/React, mostly) based in Berlin, Germany.

** Skillset **

All things JavaScript, TypeScript, React, Node, CI/CD, serverless and Kubernetes, Jenkins, testing, some product management (mainly Jira and JQL).

** Why Work With Me **

I have a background in business, media, and engineering, plus 8 years of experience with startups and consulting.

** Location **

Berlin, Germany

** LinkedIn **

https://www.linkedin.com/in/filipe-catraia-088a30170/

**Comment by Jewcub** [comment]
Are you still looking for a project? Would love to join forces! Check out the project so far at github.com/IPFC 
[medium article](https://medium.com/@jacobcohenrosenthal/searching-for-a-practical-architecture-for-a-decentralized-app-jacob-cohen-rosenthal-71af94f2e15e)

**Comment by ghost** [comment]
> Are you still looking for a project? Would love to join forces! Check out the project so far at github.com/IPFC
> [medium article](https://medium.com/@jacobcohenrosenthal/searching-for-a-practical-architecture-for-a-decentralized-app-jacob-cohen-rosenthal-71af94f2e15e)

Hi @Jewcub, thanks for reaching out! I'll think about it, but want to take some time to consider my options. Cheers!

**Comment by erin-gilly** [comment]
@filipecatraia let me know if you're open to a chat!

** Who We are **
Intimacy wellness app that helps couples with kids connect feel more like lovers and not just co-parenting roommates.

Remote first team based in Switzerland, Canada and Singapore (Background in business, sexual health / relationship well-being domain expertise, UX, product management)

** Why Work With Us **
We have more than just an idea — we have a low code MVP that couples around the world have started using already and early traction tells us that we've definitely hit on a very relevant problem to solve. That, and we're fun to work with :)

** LinkedIn **
https://www.linkedin.com/in/chenerin/
